### PR TITLE
Travis speedup

### PR DESCRIPTION
**Pull request by moreati**
Found the cause of your pytest failure: PyPy bundles an old and customised version of pytest

### CODE REVIEW

**Comment by snim2** [comment]
Awesome, many thanks!

**Comment by moreati** [comment]
Spoke too soon, from https://travis-ci.org/futurecore/revelation/builds/73694067
```
The command "python -m doctest scripts/diff_trace.py" exited with 0.
0.35s$ test "$TRANSLATE" == "true" && ${HOME}/pypy/rpython/bin/rpython --opt=jit epiphany/sim.py || true
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/travis/pypy/rpython/bin/rpython", line 13, in <module>
    from rpython.translator.goal.translate import main
  File "/home/travis/pypy/rpython/translator/goal/translate.py", line 10, in <module>
    import py
ImportError: No module named py
```

**Comment by snim2** [comment]
The translation isn't so important at the moment. I'll ask the pypy people how they deal with this stuff in their own repos. Maybe they don't install py.test from pip.

**Comment by moreati** [comment]
Okay, note that Travis install pytest themselves - so you get *some* version regardless of pip or PyPy

**Comment by snim2** [comment]
Good point.

**Comment by moreati** [comment]
There's https://pypi.python.org/pypi/rpython/ - nothing bundled, depends on pytest, last release Apr 2015. However it does say

> Warning
> This is an experimental release of a randomly chosen, untested version of RPython. Packaging issues are likely, feedback is welcome.

**Pull request merged**
